// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Logic.Context;

#nullable disable

namespace Quizzer.Logic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260327170331_gamephase")]
    partial class gamephase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Category", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CellHeight")
                        .HasColumnType("float");

                    b.Property<double>("CellWidth")
                        .HasColumnType("float");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyAddition")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyMinusAddition")
                        .HasColumnType("int");

                    b.Property<double>("DifficultyMinusMultiplier")
                        .HasColumnType("float");

                    b.Property<double>("DifficultyMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("PhaseAddition")
                        .HasColumnType("int");

                    b.Property<double>("PhaseMultiplier")
                        .HasColumnType("float");

                    b.Property<bool>("Restart")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.GameGridCoordinate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMinusPoints")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionBaseId");

                    b.ToTable("GameGridCoordinate", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Header", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeaderType")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Header", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserPictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Player", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.PlayerXGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "GameId")
                        .IsUnique();

                    b.ToTable("PlayerXGame", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CorrectAnswered")
                        .HasColumnType("bit");

                    b.Property<int>("Correction")
                        .HasColumnType("int");

                    b.Property<int>("CorrectionsCount")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameGridCoordinateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinusScore")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RightCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("WrongCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameGridCoordinateId");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionBaseId");

                    b.HasIndex("PlayerId", "QuestionBaseId", "GameId", "GameGridCoordinateId")
                        .IsUnique();

                    b.ToTable("QuestionResult", "question");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionStepResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinishType")
                        .HasColumnType("int");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResult")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceTyp")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBaseId");

                    b.ToTable("QuestionStepResource", "question");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.StepXStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FromId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("ToId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ToId");

                    b.HasIndex("FromId", "ToId")
                        .IsUnique()
                        .HasFilter("[FromId] IS NOT NULL AND [ToId] IS NOT NULL");

                    b.ToTable("StepXStep", "question");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultFinishType")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("MinusPoints")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<bool>("UseRandomSequenceOnNonFinishSteps")
                        .HasColumnType("bit");

                    b.Property<bool>("WarnOnFinishStep")
                        .HasColumnType("bit");

                    b.Property<bool>("WarnOnResultStep")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("QuestionBase", "question");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", b =>
                {
                    b.HasBaseType("Quizzer.DataModels.Models.QuestionBase");

                    b.ToTable("DefaultQuestion", "question");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("Quizzer.DataModels.Models.QuestionBase");

                    b.ToTable("MultipleChoiceQuestion", "question");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.GameGridCoordinate", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("GameGridCoordinates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", "QuestionBase")
                        .WithMany()
                        .HasForeignKey("QuestionBaseId");

                    b.Navigation("Game");

                    b.Navigation("QuestionBase");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Header", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("Headers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.PlayerXGame", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("PlayerXGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.Base.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionResult", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.GameGridCoordinate", "GameGridCoordinate")
                        .WithMany("QuestionResults")
                        .HasForeignKey("GameGridCoordinateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("QuestionResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.Base.Player", "Player")
                        .WithMany("CurrentQuestionResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", "QuestionBase")
                        .WithMany()
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameGridCoordinate");

                    b.Navigation("Player");

                    b.Navigation("QuestionBase");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionStepResource", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", null)
                        .WithMany("Steps")
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.StepXStep", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.QuestionStepResource", "From")
                        .WithMany("Froms")
                        .HasForeignKey("FromId");

                    b.HasOne("Quizzer.DataModels.Models.Base.QuestionStepResource", "To")
                        .WithMany("Tos")
                        .HasForeignKey("ToId");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", null)
                        .WithOne()
                        .HasForeignKey("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", null)
                        .WithOne()
                        .HasForeignKey("Quizzer.DataModels.Models.QuestionTypes.MultipleChoiceQuestion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Game", b =>
                {
                    b.Navigation("GameGridCoordinates");

                    b.Navigation("Headers");

                    b.Navigation("PlayerXGames");

                    b.Navigation("QuestionResults");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.GameGridCoordinate", b =>
                {
                    b.Navigation("QuestionResults");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Player", b =>
                {
                    b.Navigation("CurrentQuestionResults");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionStepResource", b =>
                {
                    b.Navigation("Froms");

                    b.Navigation("Tos");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
