// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Logic.Context;

#nullable disable

namespace Quizzer.Logic.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260305000141_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Category", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CellHeight")
                        .HasColumnType("float");

                    b.Property<double>("CellWidth")
                        .HasColumnType("float");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyAddition")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyMinusAddition")
                        .HasColumnType("int");

                    b.Property<double>("DifficultyMinusMultiplier")
                        .HasColumnType("float");

                    b.Property<double>("DifficultyMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("PhaseAddition")
                        .HasColumnType("int");

                    b.Property<double>("PhaseMultiplier")
                        .HasColumnType("float");

                    b.Property<bool>("Restart")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.GameGridCoordinate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMinusPoints")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionBaseId");

                    b.ToTable("GameGridCoordinate", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Header", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.ToTable("Header", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Player", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.PlayerXGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GamesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "GamesId")
                        .IsUnique();

                    b.ToTable("PlayerXGame", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CorrectAnswered")
                        .HasColumnType("bit");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinusScore")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestionBaseId");

                    b.ToTable("QuestionResult", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionStepResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResult")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceTyp")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SquenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBaseId");

                    b.ToTable("QuestionStepResource", "base");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("MinusPoints")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("QuestionBase", "base");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", b =>
                {
                    b.HasBaseType("Quizzer.DataModels.Models.QuestionBase");

                    b.ToTable("DefaultQuestion", "questiontype");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.GameGridCoordinate", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("GameGridCoordinates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", "QuestionBase")
                        .WithMany()
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("QuestionBase");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Header", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", null)
                        .WithMany("Columns")
                        .HasForeignKey("GameId");

                    b.HasOne("Quizzer.DataModels.Models.Base.Game", null)
                        .WithMany("Rows")
                        .HasForeignKey("GameId1");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.PlayerXGame", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("PlayerXGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.Base.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionResult", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Game", "Game")
                        .WithMany("QuestionResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.Base.Player", "Player")
                        .WithMany("CurrentQuestionResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", "QuestionBase")
                        .WithMany()
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("QuestionBase");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.QuestionStepResource", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", null)
                        .WithMany("Steps")
                        .HasForeignKey("QuestionBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.Base.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", b =>
                {
                    b.HasOne("Quizzer.DataModels.Models.QuestionBase", null)
                        .WithOne()
                        .HasForeignKey("Quizzer.DataModels.Models.QuestionTypes.DefaultQuestion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Game", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("GameGridCoordinates");

                    b.Navigation("PlayerXGames");

                    b.Navigation("QuestionResults");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.Base.Player", b =>
                {
                    b.Navigation("CurrentQuestionResults");
                });

            modelBuilder.Entity("Quizzer.DataModels.Models.QuestionBase", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
